config/routes.rb
Rails.application.routes.draw do
  resources :cart_items, only: [:show, :index]

   root 'cart_items#index'

end

app/models/cart_item.rb
class CartItem < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:show, :edit, :update, :destroy]

  # GET /cart_items
  # GET /cart_items.json
  def index
    @cart_items = CartItem.all
  end

  # GET /cart_items/1
  # GET /cart_items/1.json
  def show
  end

  # GET /cart_items/new
  # POST /cart_items
  # POST /cart_items.json

  # PATCH/PUT /cart_items/1
  # PATCH/PUT /cart_items/1.json
  # DELETE /cart_items/1
  # DELETE /cart_items/1.json
  def destroy
    @cart_item.destroy
    respond_to do |format|
      format.html { redirect_to cart_items_url, notice: 'Cart item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_item_params
      params.require(:cart_item).permit(:title, :price, :description, :imdb_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Cart Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Description</th>
      <th>Imdb</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cart_items.each do |cart_item| %>
      <tr>
        <td><%= cart_item.title %></td>
        <td><%= cart_item.price %></td>
        <td><%= cart_item.description %></td>
        <td><%= cart_item.imdb_id %></td>
        <td><%= link_to 'Show', cart_item %></td>
    <% end %>
  </tbody>
</table>

<br>

app/views/cart_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @cart_item.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @cart_item.price %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cart_item.description %>
</p>

<p>
  <strong>Imdb:</strong>
  <%= @cart_item.imdb_id %>
</p>

<%= link_to 'Back', cart_items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
    <![endif]-->

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to "eCART", root_path , class: "navbar-brand" %>
        </div>
        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path %></li>
            <li><%= link_to "Categories", "" %></li>
            <li><%= link_to "Help", "" %></li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">
      <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <%= msg %>
      <% end %>
      <% end %>

      <%= yield %>
    </div>
  </body>
  </html>